#!/bin/bash
full_path_cmd="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename $0)"

if [ -z $1 ] || [ -z $2 ]; then 
	echo "Usage: git_svn_clone_r.sh REPO_URL CLONE_DIR"
	exit;
fi
git svn clone $1 $2 || exit

# recrusively
pushd $2> /dev/null
gs-lsext | 
	while read line; do 
		# ls_git_svn_externals.sh gives "SUB_DIR REPO_URL CLONE_DIR CLONE_FULL_DIR"
		words=(${line})
		repo_r=${words[1]}
		clone_dir_r=${words[3]}
		
		eval "$full_path_cmd $repo_r $clone_dir_r"
	done
popd > /dev/null

